export const products = [
    { id: 1, title: "Wireless Headphones", price: 59.99, category: "Electronics", brand: "Nova", rating: 4.3, image: "https://picsum.photos/seed/headphones/400/400", description: "Over-ear wireless headphones with noise cancellation and 20-hour battery life." },
    { id: 2, title: "Smartwatch", price: 129.99, category: "Electronics", brand: "PixelPro", rating: 4.5, image: "https://picsum.photos/seed/smartwatch/400/400", description: "Fitness-tracking smartwatch with heart-rate monitor and always-on display." },
    { id: 3, title: "Digital Camera", price: 349.99, category: "Electronics", brand: "PixelPro", rating: 4.7, image: "https://picsum.photos/seed/camera/400/400", description: "Compact digital camera with 4K video recording and 20MP sensor." },
    { id: 4, title: "Smartphone", price: 699.0, category: "Electronics", brand: "PixelPro", rating: 4.6, image: "https://picsum.photos/seed/smartphone/400/400", description: "Flagship smartphone with a 6.5-inch display and triple-camera setup." },
    { id: 5, title: "T-Shirt", price: 19.99, category: "Clothing", brand: "Nova", rating: 4.1, image: "https://picsum.photos/seed/tshirt/400/400", description: "100% cotton crew-neck t-shirt, available in multiple colors." },
    { id: 6, title: "Running Shoes", price: 79.99, category: "Clothing", brand: "Stridewell", rating: 4.4, image: "https://picsum.photos/seed/shoes/400/400", description: "Lightweight running shoes with breathable mesh upper and cushioned sole." },
    { id: 7, title: "Sunglasses", price: 49.99, category: "Clothing", brand: "Stridewell", rating: 4.2, image: "https://picsum.photos/seed/sunglasses/400/400", description: "UV-protected polarized sunglasses with a durable metal frame." },
    { id: 8, title: "Denim Jacket", price: 89.99, category: "Clothing", brand: "Stridewell", rating: 4.3, image: "https://picsum.photos/seed/jacket/400/400", description: "Classic fit denim jacket, machine washable, unisex sizing." },
    { id: 9, title: "Backpack", price: 59.99, category: "Home", brand: "HomeCraft", rating: 4.5, image: "https://picsum.photos/seed/backpack/400/400", description: "Water-resistant backpack with padded laptop compartment." },
    { id: 10, title: "Table Lamp", price: 34.99, category: "Home", brand: "Nova", rating: 4.0, image: "https://picsum.photos/seed/lamp/400/400", description: "Adjustable LED table lamp with three brightness settings." },
    { id: 11, title: "Coffee Mug Set", price: 24.99, category: "Home", brand: "HomeCraft", rating: 4.6, image: "https://picsum.photos/seed/mug/400/400", description: "Set of 4 ceramic coffee mugs, microwave and dishwasher safe." },
    { id: 12, title: "Throw Blanket", price: 39.99, category: "Home", brand: "HomeCraft", rating: 4.4, image: "https://picsum.photos/seed/blanket/400/400", description: "Soft fleece throw blanket, perfect for couch or bed." },
];
